name: Caprover Deploy

on:
  push:
    branches: [ master ]

jobs:
  
  deploy-website:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
  
    - name: Setup NPM
      uses: actions/setup-node@v2
      with:
         node-version: '14'

    - name: Install Caprover
      run: npm install -g caprover

    - name: Caprover Deploy
      run: caprover deploy -h '${{ secrets.CAPROVER_DOMAIN }}' --appToken ${{ secrets.CAPROVER_TOKEN_WEBSITE }} -b master
      
  deploy-api:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
  
    - name: Setup NPM
      uses: actions/setup-node@v2
      with:
         node-version: '14'

    - name: Install Caprover
      run: npm install -g caprover

    - name: Caprover Deploy
      run: caprover deploy -h '${{ secrets.CAPROVER_DOMAIN }}' --appToken ${{ secrets.CAPROVER_TOKEN_API }} -b master
