name: Deploy

on:
  push:
    branches: [ master ]

jobs:

  migrations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Update Database
      working-directory: ./util/Migrations
      env: 
        ConnectionStrings__Postgres: ${{ secrets.MIGRATION_CONNECTION_STRING }}
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef database update

  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: |
          ghcr.io/tobymeehan/website

    - name: Build and Push
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        file: ./src/TobyMeehan.Com/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: [migrations, docker]

    steps:
    - name: Deploy Image to Caprover
      uses: caprover/deploy-from-github@v1.1.2
      with:
        server: "${{ secrets.CAPROVER_SERVER }}"
        app: "${{ secrets.CAPROVER_APP_NAME }}"
        token: "${{ secrets.CAPROVER_APP_TOKEN }}"
        image: ghcr.io/tobymeehan/website:main
