name: Publish

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        project: [TobyMeehan.Com, TobyMeehan.Com.Api]
    
    name: Publish ${{ matrix.project }}
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: .NET Publish
      run: dotnet publish ./${{ matrix.project }} -c Release -o ./publish/${{ matrix.project }} --verbosity normal
      
    - name: Suspend ${{ matrix.project }}
      # You may pin to the exact commit or the version.
      # uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        # FTP host
        host: ${{ secrets.FTP_SERVER }}
        # FTP user
        user: ${{ secrets.FTP_ACCOUNT_USERNAME }}
        # FTP password
        password: ${{ secrets.FTP_ACCOUNT_PASSWORD }}
        # Force SSL encryption
        forceSsl: false
        # Local directory
        localDir: ./Deploy
        # Remote directory
        remoteDir: /${{ matrix.project }}
    
    - name: FTP Deploy
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        # FTP host
        host: ${{ secrets.FTP_SERVER }}
        # FTP user
        user: ${{ secrets.FTP_ACCOUNT_USERNAME }}
        # FTP password
        password: ${{ secrets.FTP_ACCOUNT_PASSWORD }}
        # Force SSL encryption
        forceSsl: false
        # Local directory
        localDir: ./publish/${{ matrix.project }}
        # Remote directory
        remoteDir: /${{ matrix.project }}
        
    - name: Activate ${{ matrix.project }}
      # You may pin to the exact commit or the version.
      # uses: StephanThierry/ftp-delete-action@63dccfa5942a4a11f5d85a98f99f89ad588326d4
      uses: StephanThierry/ftp-delete-action@v1
      with:
        # FTP host
        host: ${{ secrets.FTP_SERVER }}
        # FTP user
        user: ${{ secrets.FTP_ACCOUNT_USERNAME }}
        # FTP password
        password: ${{ secrets.FTP_ACCOUNT_PASSWORD }}
        # Remote files seperated by ; (wildcards accepted)
        remoteFiles: "${{ matrix.project }}/app_offline.htm"
        # Working directory
        # workingDir:
        # Ignore invalid TLS/SSL certificate (1=ignoreSSL)
        ignoreSSL: "1"
        
        
        
