name: Docker DO Publish

on:
  push:
    branches: [ master ]

jobs:

  website:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: GitHub Action for DigitalOcean - doctl
      # You may pin to the exact commit or the version.
      # uses: digitalocean/action-doctl@d36a87b1d9c7bd55c8d8434ff2a991a6ee32a448
      uses: digitalocean/action-doctl@v2.1.0
      with:
        # Version of doctl to install
        version: latest # optional, default is latest
        # DigitalOcean API Token
        token: ${{ secrets.DIGITALOCEAN_API_KEY }}
    
    - name: DigitalOcean Docker Image Publish
      # You may pin to the exact commit or the version.
      # uses: ripplr-io/docr-docker-publish@44fac8d6ff7c3ece58c9ffe50f370514d166f5b7
      uses: ripplr-io/docr-docker-publish@v1
      with:
        # Image path in the format registry-name/image-name
        image_path: tobymeehan/tobymeehan-com
        # Number of characters from the commit SHA
        sha_size: 8 # optional, default is 8
        # The path + name of the Dockerfile you want to build (-f flag)
        dockerfile: ./TobyMeehan.Com/Dockerfile # optional, default is Dockerfile
        # The docker build context (usually '.')
        docker_build_context: . # optional, default is .
        
  api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: GitHub Action for DigitalOcean - doctl
      # You may pin to the exact commit or the version.
      # uses: digitalocean/action-doctl@d36a87b1d9c7bd55c8d8434ff2a991a6ee32a448
      uses: digitalocean/action-doctl@v2.1.0
      with:
        # Version of doctl to install
        version: latest # optional, default is latest
        # DigitalOcean API Token
        token: ${{ secrets.DIGITALOCEAN_API_KEY }}
    

    - name: DigitalOcean Docker Image Publish
      # You may pin to the exact commit or the version.
      # uses: ripplr-io/docr-docker-publish@44fac8d6ff7c3ece58c9ffe50f370514d166f5b7
      uses: ripplr-io/docr-docker-publish@v1
      with:
        # Image path in the format registry-name/image-name
        image_path: tobymeehan/tobymeehan-api
        # Number of characters from the commit SHA
        sha_size: 8 # optional, default is 8
        # The path + name of the Dockerfile you want to build (-f flag)
        dockerfile: ./TobyMeehan.Com.Api/Dockerfile # optional, default is Dockerfile
        # The docker build context (usually '.')
        docker_build_context: . # optional, default is .
