name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  website:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.8
    
    - name: Install Dependencies
      run: dotnet restore      

    - name: .NET Publish
      run: dotnet publish ./TobyMeehan.Com -c Release -o ./publish/TobyMeehan.Com --no-restore --verbosity normal
    
    - name: FTP Deploy
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        # FTP host
        host: ${{ secrets.FTP_SERVER }}
        # FTP user
        user: ${{ secrets.FTP_ACCOUNT_USERNAME }}
        # FTP password
        password: ${{ secrets.FTP_ACCOUNT_PASSWORD }}
        # Force SSL encryption
        forceSsl: false
        # Local directory
        localDir: ./publish/TobyMeehan.Com
        # Remote directory
        remoteDir: /AspNetCore/httpdocs
  
  webapi:
    name: Deploy Web API
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.8
      
      - name: Install Dependencies
        run: dotnet restore
      
      - name: .NET Publish
        run: dotnet publish ./TobyMeehan.Com.Api -c Release -o ./publish/TobyMeehan.Com --no-restore --verbosity normal
      
      - name: FTP Deploy
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          # FTP host
          host: ${{ secrets.FTP_SERVER }}
          # FTP user
          user: ${{ secrets.FTP_ACCOUNT_USERNAME }}
          # FTP password
          password: ${{ secrets.FTP_ACCOUNT_PASSWORD }}
          # Force SSL encryption
          forceSsl: false
          # Local directory
          localDir: ./publish/TobyMeehan.Com
          # Remote directory
          remoteDir: /AspNetCore/api
        
